trigger:
- main

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '1e89d218-6ad9-4b17-a8c2-f16d71de181a'
  imageRepository: 'foodhub'
  containerRegistry: 'foodhubacr12345.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'foodhubacr123452969-auth'

  vmImageName: 'ubuntu-latest'

  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))

    pool:
      vmImage: $(vmImageName)

    environment: 'yashwanthsaid924artFoodHubDevOps.default'

    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

  - deployment: DeployPullRequest
    displayName: Deploy Pull Request
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))

    pool:
      vmImage: $(vmImageName)

    environment: 'yashwanthsaid924artFoodHubDevOps.$(k8sNamespaceForPR)'

    strategy:
      runOnce:
        deploy:
          steps:

          - reviewApp: default

          - task: Kubernetes@1
            displayName: Create PR Namespace
            inputs:
              command: apply
              useConfigurationFile: true
              inline: |
                {
                  "kind":"Namespace",
                  "apiVersion":"v1",
                  "metadata":{
                    "name":"$(k8sNamespaceForPR)"
                  }
                }

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: $(k8sNamespaceForPR)
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy Review App
            inputs:
              action: deploy
              namespace: $(k8sNamespaceForPR)
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)