apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodhub-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodhub-app
  template:
    metadata:
      labels:
        app: foodhub-app
    spec:
      containers:
      - name: foodhub-container
        image: foodhubacr12345.azurecr.io/foodhub:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080